# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Spinning Numbers
email: willy@spinningnumbers.org
author: 'Willy McAllister'

description: > # this means to ignore newlines until "baseurl:"
  Learn electrical engineering.  

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spinningnumbers.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  willymcallister
youtube_username: channel/UCCpZqoONJn-JcSRl-Y3_KXw
facebook_username: spinningnumbers
linkedin_username: williamhmcallister
quora_username: Willy-McAllister

# Build settings
markdown: kramdown
github: [metadata]
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-91424157-1

# Staticman comments
#staticmanUrl: https://api.staticman.net/v3/entry/github/willymcallister/willymcallister.github.io/master/comments
staticmanUrl: https://spinningnumbers-staticmandev2.herokuapp.com/v2/entry/willymcallister/willymcallister.github.io/master/comments
#staticmanUrl: https://spinningnumbers-staticmandev.herokuapp.com/v3/entry/github/willymcallister/willymcallister.github.io/master/comments
enableComments: true

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LcK3xkUAAAAAKdppIIORt78Df93D2qvOGtZinEy"
  secret: "hh/dk2ufAAaq3uw9xZHa0T701UUJs2FUwnFkDJ+FxfQmGNYB3c0OmZafYvsUQR3XhVL8FNqy7bfXePf1tC2EiyHOxu1IFiX1DpEoDe+95BRyWPc5+r7Pix0gjMdL3K/RQx/+EmANKlY/el8U3VZh+dRGXDkMWwUgcj+3nvZmAJLR5X3dHkZ+1fswtWymUSZqq6DdfeHxrsKmyjkZaiLvF/J7jROTtBFiLwgMkUp2vT+Jyl0AUXAE6Lq1b77B8ehI67FsqtpsHYGBiAWDH0BLb0F1ryDIHU4twtJYr+DEioFY4OeQoQdB2ZbflAsInitP1Wo1bguyuqo2TGgMIci5+euKSP3TNZfId6QQxYS6AFU39NhB4cKiOHln2/bEtwm+0rZAEZwMwsws5oPS45twNl2oqNSuspxexDeqXmXLi/arvBi60ArToO0WQOm58a132M/DXojhMD4t7rDK2+PUHMQjnfTSphhsAETScxbXbSqp6e/sdVLvxw4S0B9EeHf7VMasyMJaxHpZjJRl6N5P6itQH7HHwaOXJ1gfk04TR2H1BLqPpUl99NbjesP4rdXda2mSaOIwIdE26Em3rhLoB6Rm9zo2niUwNre41BSdrzwd8gqPGP5oq2HF4/7lRGs9fxmsTdWWQDlYFJaaW02do+eZ1N8TCvL6LHSXkhSJETw="
collections:
  videos:
    output: true
    permalink: /v/:title:output_ext
  articles:
    output: true
    permalink: /a/:title:output_ext
  topics:
    output: true
    permalink: /t/:title:output_ext
  drafts:
    output: true
    permalink: /drafts/:title:output_ext

defaults:
  - scope:
      path: "i"
    values:
      image: true

timezone: America/Los_Angeles

# Referenced by Jekyll-SEO-tag plug-in
logo: "/assets/logo.png"
